config/routes.rb
MetroApp::Application.routes.draw do
  get "missions/cancel"
  get "helps/index"
  post "missions/capture"
  get "action_histories/get_image"
  post "missions/upload"
  delete "action_histories/destroy"
  post "missions/trip_infomations_api"
  get "action_histories/index"
  get "action_histories/trip_histories_api"
  get "missions/mission_list_api"
  get "missions/progress"
  get "missions/index"
  get "missions/show"
  post "missions/create"
  delete "missions/destroy"
  post "missions/complete"

  root 'sessions#index'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get]
  match 'auth/failure', to: 'sessions#failure', via: [:get]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:delete]

end

app/helpers/missions_helper.rb
# encoding: utf-8

module MissionsHelper
  # 東京メトロAPI, 柳岡APIへリクエストするクライアント
  def http_client(url)
    client = Faraday.new(:url => url) do |faraday|
      faraday.request  :url_encoded             # form-encode POST params
      faraday.response :logger                  # log requests to STDOUT
      faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
    end
    return client
  end

  # 上りと下りの時刻表を取得する
  def acquire_train_time(station)
    result = Hash.new

    now_time = Time.now.in_time_zone('Tokyo') 
    hour_minute = now_time.strftime("%H:%M") 
    day = now_time.strftime("%w")  # 0-6 日曜が0

    client = http_client(DATAPOINTS_URL)

    response = client.get DATAPOINTS_URL,
                 {'rdf:type' => 'odpt:StationTimetable',
                  'odpt:station' => 'odpt.Station:' + station,
                  'acl:consumerKey' => ACCESS_TOKEN} 
    parse_result = JSON.parse(response.body)

    days = "odpt:weekdays"
    
    # TODO: 平日と土日祝日の判定が必要
    # 平日: odpt:weekdays
    # 土日: odpt:saturdays
    # 祝日: odpt:holidays

    case day
    when "0", "6" then
      days = "odpt:saturdays"
    when "holidays" then
      days = "odpt:holidays"
    end

    if station == 'TokyoMetro.Ginza.Shibuya'
      # 0 渋谷方面
      up_time_array = []
      parse_result[0][days].each do |hash|
        time_table = hash["odpt:departureTime"]

        if hour_minute < time_table
          up_time_array << time_table
          break if up_time_array.size == 3
        end
      end

      down_time_array = []
      3.times do 
        down_time_array << '--:--'
      end
    elsif station == 'TokyoMetro.Ginza.Asakusa'
      # 1 浅草方面
      down_time_array = []
      parse_result[0][days].each do |hash|
        time_table = hash["odpt:departureTime"]

        if hour_minute < time_table
          down_time_array << time_table
          break if down_time_array.size == 3
        end
      end

      up_time_array = []
      3.times do 
        up_time_array << '--:--'
      end
    else
      # 0 渋谷方面
      up_time_array = []
      parse_result[0][days].each do |hash|
        time_table = hash["odpt:departureTime"]

        if hour_minute < time_table
          up_time_array << time_table
          break if up_time_array.size == 3
        end
      end
      # 1 浅草方面
      down_time_array = []
      parse_result[1][days].each do |hash|
        time_table = hash["odpt:departureTime"]

        if hour_minute < time_table
          down_time_array << time_table
          break if down_time_array.size == 3
        end
      end
    end

    result = {
      up: up_time_array,
      down: down_time_array
    }
  end

  # 駅名の一覧を取得
  def acquire_station_name
    client = http_client(DATAPOINTS_URL)

    target_railway = '銀座'
    response = client.get DATAPOINTS_URL,
                 {'rdf:type' => 'odpt:Railway',
                  'dc:title' => target_railway,
                  'acl:consumerKey' => ACCESS_TOKEN} 
    result = JSON.parse(response.body)[0]["odpt:stationOrder"]
  end

  # 駅名を保持するハッシュを生成する
  def acquire_station_name_hash
    prefix = 'odpt.Station:TokyoMetro.Ginza.'

    result = {
        prefix + "Shibuya" => { name: "渋谷", enable: true, no: '01' },
        prefix + "OmoteSando" => { name: "表参道", enable: true, no: '02' },
        prefix + "Gaiemmae" => { name: "外苑前", enable: false, no: '03' },
        prefix + "AoyamaItchome" => { name: "青山一丁目", enable: true, no: '04' },
        prefix + "AkasakaMitsuke" => { name: "赤坂見附", enable: false, no: '05' },
        prefix + "TameikeSanno" => { name: "溜池山王", enable: false, no: '06' },
        prefix + "Toranomon" => { name: "虎ノ門", enable: true, no: '07' },
        prefix + "Shimbashi" => { name: "新橋", enable: false, no: '08' },
        prefix + "Ginza" => { name: "銀座", enable: true, no: '09' },
        prefix + "Kyobashi" => { name: "京橋", enable: false, no: '10' },
        prefix + "Nihombashi" => { name: "日本橋", enable: true, no: '11' },
        prefix + "Mitsukoshimae" => { name: "三越前", enable: false, no: '12' },
        prefix + "Kanda" => { name: "神田", enable: false, no: '13' },
        prefix + "Suehirocho" => { name: "末広町", enable: true, no: '14' },
        prefix + "UenoHirokoji" => { name: "上野広小路", enable: true, no: '15' },
        prefix + "Ueno" => { name: "上野", enable: false, no: '16' },
        prefix + "Inaricho" => { name: "稲荷町", enable: true, no: '17' },
        prefix + "Tawaramachi" => { name: "田原町", enable: false, no: '18' },
        prefix + "Asakusa" => { name: "浅草", enable: true, no: '19' }
    }
  end

  # 引数に指定した駅のミッションの一覧を取得する
  def get_mission_list(station_no)

    parse_result = mission_infomations_get(station_no: station_no)

    result = []
    parse_result.each do | mission |
      # キーをシンボルに変換
      # TODO: 第二階層目以降は変換されない
      result << mission.symbolize_keys
    end

    result
  end

  # 現在の駅番号を取得する
  def current_station
    current_trip = current_trip(current_user[:user_no])

    if current_trip.present? && current_trip[:status] == PROGRESS
      req = {
        user_no: current_user[:user_no],
        trip_no: current_trip[:trip_no]
      }
      current_trip_histories = current_trip_history(current_user[:user_no], current_trip[:trip_no])
      station_no = (current_trip_histories[:station_no].to_i if !current_trip_histories.nil?) || FIRST_TRAIN_NO 
    else
      station_no = FIRST_TRAIN_NO 
    end
  end

  # 直前の駅番号を取得する
  def before_station
    current_trip = current_trip(current_user[:user_no])

    req = {
      user_no: current_user[:user_no],
      trip_no: current_trip[:trip_no]
    }
    # 旅履歴から2番目の履歴を取得する
    before_trip_history = trip_histories_get(req)[1]

    if before_trip_history.present? 
      station_no = before_trip_history.symbolize_keys[:station_no].to_i 
    else
      station_no = FIRST_TRAIN_NO 
    end
  end

  # 最新の旅情報を取得する
  def current_trip(user_no)
    current_trip = trip_infomations_get(user_no: user_no).first
    current_trip = current_trip.symbolize_keys if !current_trip.nil?
  end

  # 最新の旅履歴情報を取得する
  def current_trip_history(user_no, trip_no)
    req = {
      user_no: user_no,
      trip_no: trip_no
    }
    current_trip_histories = trip_histories_get(req).first
    current_trip_histories = current_trip_histories.symbolize_keys if !current_trip_histories.nil?
  end

  # 駅番号に対応する駅キーを返す
  def get_station_key(station_no)
    # 銀座線で固定
    prefix = 'TokyoMetro.Ginza.'

    # 駅のキーを初期化
    station_map = {
        1 => prefix + "Shibuya",
        2 => prefix + "OmoteSando",
        3 => prefix + "AoyamaItchome",
        4 => prefix + "Toranomon",
        5 => prefix + "Ginza",
        6 => prefix + "Nihombashi",
        7 => prefix + "Suehirocho",
        8 => prefix + "UenoHirokoji",
        9 => prefix + "Inaricho",
        10 => prefix + "Asakusa"
    }
=begin
    station_map = {
        1 => prefix + "Shibuya",
        2 => prefix + "OmoteSando",
        3 => prefix + "Gaiemmae",
        4 => prefix + "AoyamaItchome",
        5 => prefix + "AkasakaMitsuke",
        6 => prefix + "TameikeSanno",
        7 => prefix + "Toranomon",
        8 => prefix + "Shimbashi",
        9 => prefix + "Ginza",
        10 => prefix + "Kyobashi",
        11 => prefix + "Nihombashi",
        12 => prefix + "Mitsukoshimae",
        13 => prefix + "Kanda",
        14 => prefix + "Suehirocho",
        15 => prefix + "UenoHirokoji",
        16 => prefix + "Ueno",
        17 => prefix + "Inaricho",
        18 => prefix + "Tawaramachi",
        19 => prefix + "Asakusa"
    }
=end

    station_map[station_no.to_i]
  end

  # 駅番号に対応する駅名を返す
  def get_station_name(station_no)
    nameMap = {
        1 => "渋谷",
        2 => "表参道",
        3 => "青山一丁目",
        4 => "虎ノ門",
        5 => "銀座",
        6 => "日本橋",
        7 => "末広町",
        8 => "上野広小路",
        9 => "稲荷町",
        10 => "浅草"
    }
=begin
    nameMap = {
        1 => "渋谷",
        2 => "表参道",
        3 => "外苑前",
        4 => "青山一丁目",
        5 => "赤坂見附",
        6 => "溜池山王",
        7 => "虎ノ門",
        8 => "新橋",
        9 => "銀座",
        10 => "京橋",
        11 => "日本橋",
        12 => "三越前",
        13 => "神田",
        14 => "末広町",
        15 => "上野広小路",
        16 => "上野",
        17 => "稲荷町",
        18 => "田原町",
        19 => "浅草"
    }
=end
    nameMap[station_no]
  end
end

app/views/missions/_station_info.html.erb
<div style="height: 150px; width: 210px; margin: 25px 0 15px; border-color: rgb(255, 218, 192);">
  <div style="height: 100%; width: 100%; margin: 0; border-color: rgb(255, 218, 192);">
    <ul class="list-box" style="padding: 0px 5px;">
      <% @station_name_array.each_with_index do |station| %>
        <% if @station_name_hash[station["odpt:station"]][:enable] %>
          <li class="list-text" style="width: 15px;font-size: 18px;">
            <img src="/assets/station/st_<%= @station_name_hash[station["odpt:station"]][:no] %>.png" border="0" id="img_station" style="position:absolute;" height="20" width="20">
            <div class="enable-station"
                 style="background-color: orange; width: 18px; height: 18px; margin: 0 0;">&nbsp;</div>
          <%= @station_name_hash[station["odpt:station"]][:name] %>
          </li>
          <% if @station_name_hash[station["odpt:station"]][:name] != "浅草"%>
            <li class="list-text" style="font-size: 3px; width: 10px;">
                <div style="background-color: #4C4747; width: 14px; height: 5px; margin: 0 0;">&nbsp;</div>
            </li>
          <% end %>
        <% end %>
      <% end %>
    </ul>
  </div>
  <img src="/assets/train/train.png" border="0" id="img_user" style="position:absolute;" height="20">
  <div id="station_info" class="display-none-style"
    data-current-station-no="<%= @current_station_info[:station_no] %>"
    data-next-station-no="<%= @next_station_info[:station_no] if @next_station_info.present? %>" >
  </div>
</div>

<style>
div.tate-area{
  float: left;
  font-size:12pt;
  height: 100%;
  overflow: auto;
}
div.tate-line{
  height: 115px;
  float: left;
  width:1.05em;
  line-height:1.05em;
  margin-right:0.3em;
  margin-left:0.3em;
  padding-bottom:0.2em;
/*  font-family:'ヒラギノ角ゴ ProN','Hiragino Kaku Gothic ProN','ヒラギノ角ゴ Pro','Hiragino Kaku Gothic Pro','メイリオ','Meiryo','ＭＳ ゴシック','MS Gothic','SimHei','HiraKakuProN-W3','STHeitiJ-Medium','TakaoExゴシック','TakaoExGothic','MotoyaLCedar','Droid Sans Japanese','Droid Sans Fallback',monospace;*/
  word-wrap:break-word;
  direction:ltr;
  margin-bottom: 5px;
}
.station-mark {
  height: 25px;
  margin: 5px;
  background-color: orange;
}
.station-mark-arrow {
  height: 25px;
  margin: 5px;
}
div.tate-line-arrow{
  height: 115px;
  float: left;
  width:1.05em;
  line-height:1.05em;
/*  margin-right:0.3em;
  margin-left:0.3em;*/
  padding-bottom:0.2em;
/*  font-family:'ヒラギノ角ゴ ProN','Hiragino Kaku Gothic ProN','ヒラギノ角ゴ Pro','Hiragino Kaku Gothic Pro','メイリオ','Meiryo','ＭＳ ゴシック','MS Gothic','SimHei','HiraKakuProN-W3','STHeitiJ-Medium','TakaoExゴシック','TakaoExGothic','MotoyaLCedar','Droid Sans Japanese','Droid Sans Fallback',monospace;*/
  word-wrap:break-word;
  direction:ltr;
  margin-bottom: 5px;
}

.list-box {
  display: table;
  height: 100%;
  width: 150%;
}
.list-img,
.list-text {
  display: table-cell;
  /*vertical-align: middle;*/
 /* width: 14px;*/
}
.display-none-style {
  display: none;
}
</style>

app/views/missions/capture.html.erb
<div id="photo_part" style="width: 300px; margin: 0 auto; padding: 15px 0;">
  <img src="data:<%= @upload_photo[:photo_name] %>;base64, <%= @upload_photo[:photo_content] %>" width='300'>
  <%= form_tag 'upload', enctype: "multipart/form-data" do %>
    <%= hidden_field_tag 'station_no',  @data[:station_no] %>
    <%= hidden_field_tag 'mission_no',  @data[:mission_no] %>

    <%= submit_tag 'preview', id: 'submit_btn', class: "display-none-style loading-confirm",
                              confirm: "アップロードしてもいいですか？" %>
  <% end %>
</div>

<div style="width: 300px; margin: 0 auto;">
  <%= link_to "キャンセル", missions_cancel_path(@data), class: "btn btn-primary loading" %>
  <%= link_to "アップロード", '#', id: 'upload_btn',
                            class: "btn btn-primary", style: "float: right;"%>
</div>


<script>
$(function(){
  $('nav').remove();
  $('#footer').remove();

  $('#upload_btn').click(function(){
    $('#submit_btn').click();
  });
})
</script>
<style>
.display-none-style {
  display: none;
}
</style>

app/views/missions/mission_list_api.erb
<div id="mission_data" style="height: 160px; overflow: auto;">
  <% @json.each do |mission| %>
  <div class="mission-info" style="border: 1px solid white; height: 37px;" 
       data-station-no=<%= mission[:station_no]%> data-target-place-no=<%= mission[:target_place_no]%> >
    <span><%= mission[:title] %></span>
    <span style="float: right;">
      <%= link_to image_tag('mission/image_' + mission[:station_no] + '_' + mission[:target_place_no] + '.jpg',
                             border: 0, size: '40x33'),
          missions_show_path(station_no: mission[:station_no], mission_no: mission[:mission_no], target_place_no: mission[:target_place_no]),
          class: "btn btn-primary", style: "padding: 0px; margin: 0px;" %>
    </span>
  </div>
  <% end %>
</div>                             

app/views/missions/mission_list_api.html.erb
<div id="mission_data" style="height: 175px; overflow: auto;">
  <% @json.each do |mission| %>
    <div class="col-xs-6 col-sm-6 col-md-4">
      <div class="mission-info" data-station-no=<%= mission[:station_no]%>
           data-mission-no=<%= mission[:mission_no]%> >
        <div class="thumbnail" style="">
          <%= link_to image_tag(mission[:mission_image_url],
                      border: 0, size: '119x95', style:'border-radius: 5px'),
                      missions_show_path(station_no: mission[:station_no], mission_no: mission[:mission_no]),
                      style: "display: block; padding: 0px; margin: 0px;",
                      class: "loading" %>
          <div class="caption" style="padding: 0; text-align: center; min-height: 40px;">
            <p><%= mission[:mission_title] %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/missions/progress.html.erb
<div>
  <div style="width: 97%; margin: 5px auto -10px auto;">
    <div style="height: 100%; width: 100%; margin: 0 auto; font-size: 11px; height: 110px;">
      <div class="panel panel-success">
        <div class="panel-heading" style="background-color:#2fa4e7">
           <span>「<%= @current_station_info[:station_name] %></span><span>駅」から</span>
           <span>「<%= @next_station_info[:station_name] %></span><span>駅」へ移動中</span>
        </div>
        <table class="table">
          <tbody>
            <tr>
              <td rowspan="2"><%= @current_station_info[:station_name] %>駅発 </td>
              <td>浅草方面</td>
              <% @train_time[:up].each do |up_time| %>
                <td><%= up_time %></td>
              <% end %>
            </tr>
            <tr>
              <td>渋谷方面</td>
              <% @train_time[:down].each do |down_time| %>
                <td><%= down_time %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <%= render 'missions/station_info' %>

  <div style="margin: 5px 0px; height: 100%; width: 100%; font-size: 15px; height: 25px;">
    <p class="bg-primary">思い出を記録</p>
  </div>

    <div class="box_camera" style="display: table;">
      <div style="display: table-cell">
        <%= form_tag 'capture', enctype: "multipart/form-data" do %>
          <%= hidden_field_tag 'trip_no', @current_trip_info[:trip_no] %>
          <%= hidden_field_tag 'do_no',  @current_trip_info[:do_no] %>
          <%= hidden_field_tag 'station_no',  @data[:station_no] %>
          <%= hidden_field_tag 'mission_no',  @data[:mission_no] %>

          <div style="height:1px;width:1px;overflow:hidden;margin-left:-999px">
            <input id="photo_content" name="photo_content" type="file" accept="image/*">
          </div>
          <div>
            <%= image_tag asset_path("camera.png"), {id: 'camera_btn', width: '60'} %>
          </div>
          <%= submit_tag 'preview', id: 'submit_btn', class: "display-none-style loading" %>
        <% end %>
      </div>
      <div style="display: table-cell">
        <p style="margin: 0 5px 0;">カメラで撮影して、</p>
        <p style="margin: 0 5px;">思い出に残そう！</p>
      </div>
    </div>

  <div style="margin: 5px 0px; height: 100%; width: 100%; font-size: 15px; height: 25px;">
    <p class="bg-primary">実行中のミッション</p>
  </div>

  <div style="margin: 5px; height: 165px; width: 85%; margin: 10px 25px; font-size: 15px;">
    <div class="caption" style="padding: 0;">
       <h4 style="margin: 5px;"><%= @mission_info[:mission_title] %></h4>
    </div>
    <div style="display: table;">
      <div style="display: table-cell">
        <%= link_to image_tag(@mission_info[:mission_image_url], border: 0, size: '90x72', style:'border-radius: 5px'),
                    missions_show_path(@mission_info),
                    style: "display: block; padding: 0px; margin: 3px;" %>
      </div>
      <div style="display: table-cell; position: relative; top: -25px;">
       <p><%= @mission_info[:mission_summary] %></p>
    </div>
    </div>
  </div>
  <div style="margin: 5px; height: 100%; width: 100%; margin: 0 auto; font-size: 15px; height: 25px;">
    <p class="bg-primary">目的地情報</p>
  </div>

  <div style="background-color: white; padding-top: 1px; margin: 10px 25px 25px 25px;">
    <div>
      <%= image_tag @target_place_detail[:target_place_image_url],
                    border: 0, size: '272x146', style:'border-radius: 10px' %>
    </div>
    <div class="title" style=" height: 20px; margin: 1px auto;">
      <h4 style="margin: 5px;"><%= @target_place_detail[:name] %></h4>
    </div>

    <div class="destination-info" style="border: 1px; height: 80px; margin: 10px;">
        <div style="height: 100%;">
                <div>
          <span>住所: </span>
          <span><%= @target_place_detail[:address] %></span>
                </div>
                <div>
          <span>電話番号: </span>
          <span><%= @target_place_detail[:tel] %></span>
                </div>
                <div>
          <%= link_to 'MAP', '#', id: "map_btn", "data-tooltip" => "#html_map", class: "btn btn-info" %>
          <div id="html_map" style="display: none;">
            <%=  image_tag 'map/' + @target_place_detail[:map_url], border: 0, size: '250x250' %>
          </div>
          </div>
      </div>
    </div>

    <div class="mission-detail" style=" height: 50px; margin: 10px;">
        <p><%= @target_place_detail[:abustract] %></p>
    </div>
  </div>

  <div class="btn-field" style="margin: 5px; padding: 5px;">
  	<div style="width: 90%; margin: 0 auto;">
      <%= link_to "ミッション変更",
          missions_destroy_path(@data), method: :delete, class: "btn btn-primary loading-confirm",
          style: "float: left; margin-right: 10px;", confirm: "進行中のミッションを変更しますか？" %>
      <%= button_to "ミッション達成", missions_complete_path(@data), class: "btn btn-primary loading-confirm", confirm: "ミッションを達成しましたか？" %>
    </div>
  </div>

</div>

<script>
  $(function(){
    $('#camera_btn').click(function() {
      $("#photo_content").trigger('click');
    });

    $('#photo_content').change(function(){
      $('#submit_btn').click();
    });
  })
</script>
<style>
div.tate-area{
  float: left;
  font-size:12pt;
  height: 100%;
  overflow: auto;
}
div.tate-line{
  height: 115px;
  float: left;
  width:1.05em;
  line-height:1.05em;
  margin-right:0.3em;
  margin-left:0.3em;
  padding-bottom:0.2em;
/*  font-family:'ヒラギノ角ゴ ProN','Hiragino Kaku Gothic ProN','ヒラギノ角ゴ Pro','Hiragino Kaku Gothic Pro','メイリオ','Meiryo','ＭＳ ゴシック','MS Gothic','SimHei','HiraKakuProN-W3','STHeitiJ-Medium','TakaoExゴシック','TakaoExGothic','MotoyaLCedar','Droid Sans Japanese','Droid Sans Fallback',monospace;*/
  word-wrap:break-word;
  direction:ltr;
  margin-bottom: 5px;
}
.station-mark {
  height: 25px;
  margin: 5px;
  background-color: orange;
}
.station-mark-arrow {
  height: 25px;
  margin: 5px;
}
div.tate-line-arrow{
  height: 115px;
  float: left;
  width:1.05em;
  line-height:1.05em;
/*  margin-right:0.3em;
  margin-left:0.3em;*/
  padding-bottom:0.2em;
/*  font-family:'ヒラギノ角ゴ ProN','Hiragino Kaku Gothic ProN','ヒラギノ角ゴ Pro','Hiragino Kaku Gothic Pro','メイリオ','Meiryo','ＭＳ ゴシック','MS Gothic','SimHei','HiraKakuProN-W3','STHeitiJ-Medium','TakaoExゴシック','TakaoExGothic','MotoyaLCedar','Droid Sans Japanese','Droid Sans Fallback',monospace;*/
  word-wrap:break-word;
  direction:ltr;
  margin-bottom: 5px;
}
div.box_camera {
  margin-left:20px;
}
</style>

app/views/missions/show.html.erb
<div style="margin: 5px; height: 100%; width: 100%; margin: 0 auto; font-size: 15px; height: 25px;">
  <p class="bg-primary">ミッション情報</p>
</div>

<div style="margin: 5px; height: 140px; width: 85%; margin: 10px 25px; font-size: 15px;">
  <div class="caption" style="padding: 0;">
     <h4 style=" margin: 5px;"><%= @mission_info[:mission_title] %></h4>
  </div>
       <%= link_to image_tag(@mission_info[:mission_image_url],
                      border: 0, size: '119x95', style:'border-radius: 5px'),
                      missions_show_path(@mission_info),
                      style: "display: block; padding: 0px; margin: 3px;float:left;" %>
       <div style="margin: 10px;float:left; width: 125px;">
         <p><%= @mission_info[:mission_summary] %></p>
       </div>
</div>

<div style="margin: 5px; height: 100%; width: 100%; margin: 10px 0 auto; font-size: 15px; height: 25px;clear:left;">
  <p class="bg-primary">目的地情報</p>
</div>
<div style="background-color: white; padding-top: 1px; margin: 10px 25px; ">
  <div>
    <%= image_tag @target_place_detail[:target_place_image_url], border: 0, size: '272x146', style:'border-radius: 10px' %>
  </div>
  <div class="title" style=" height: 20px; margin: 1px auto;">
    <h4 style=" margin: 5px;"><%= @target_place_detail[:name] %></h4>
  </div>

  <div class="destination-info" style="border: 1px; height: 80px; margin: 5px;">
  	<div style="height: 100%; margin: 5px;">
  	  	<div>
          <span>住所: </span>
          <span><%= @target_place_detail[:address] %></span>
  	  	</div>
  	  	<div>
          <span>電話番号: </span>
          <span><%= @target_place_detail[:tel] %></span>
  	  	</div>
  	  	<div>
          <%= link_to 'MAP', '#', id: "map_btn", "data-tooltip" => "#html_map", class: "btn btn-info" %>
          <div id="html_map" style="display: none;">
            <%=  image_tag 'map/' + @target_place_detail[:map_url], border: 0, size: '250x250' %>
          </div>
  	  </div>
    </div>
  </div>

  <div class="mission-detail" style=" height: 50px; margin: 10px;">
      <p><%= @target_place_detail[:abustract] %></p>
  </div>

  <div class="btn-field" style="margin: 0 auto; padding: 5px; width: 70%;">
    <%= link_to "キャンセル", missions_index_path, class: "btn btn-primary loading",
        style: "margin-right: 10px; float: left;" %>
    <%= button_to "決定", missions_create_path(@data), class: "btn btn-primary loading-confirm",
        confirm: "ミッションを決定してもいいですか？" %>
  </div>
</div>