config/routes.rb
MetroApp::Application.routes.draw do
  get "missions/cancel"
  get "helps/index"
  post "missions/capture"
  get "action_histories/get_image"
  post "missions/upload"
  delete "action_histories/destroy"
  post "missions/trip_infomations_api"
  get "action_histories/index"
  get "action_histories/trip_histories_api"
  get "missions/mission_list_api"
  get "missions/progress"
  get "missions/index"
  get "missions/show"
  post "missions/create"
  delete "missions/destroy"
  post "missions/complete"

  root 'sessions#index'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get]
  match 'auth/failure', to: 'sessions#failure', via: [:get]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:delete]

end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div id="footer">
  <div class="row">
    <div class="col-md-12">
      <div class="footer">
        <div class="container">
          <div class="footer-copyright text-center">Copyright &copy; 2014 Kazuhiro.Y Aya.K Ryota.S </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<!--nav-->
<nav class="navbar navbar-default navbar-custom" role="navigation"
     style="border-radius: 0px; margin-bottom: 0px;">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse"
              data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=<%= root_path %> 
         style="padding-top: 5px; padding-bottom: 5px;">
        <img src=<%= asset_path "tokyometro_logo.jpg" %> height="40">
      </a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if session[:uid].present? %>
          <li><%= link_to "トップ画面", missions_index_path(@data), class: "nav-link text-center loading" %></li>
          <li><%= link_to "旅の履歴", action_histories_index_path(@data), class: "nav-link text-center loading" %></li>
          <% if current_trip(current_user[:user_no]).present? && current_trip(current_user[:user_no])[:status] == "1"  %>
            <li><%= link_to "現在の旅を終了する", action_histories_destroy_path(current_user),
                    class: "nav-link text-center loading-confirm", method: "delete", confirm: "旅を終了しますか?" %></li>
          <% end %>
          <li><%= link_to "ヘルプ", helps_index_path, class: "nav-link text-center loading" %></li>
          <li><%= link_to "ログアウト", signout_path, method: "delete", class: "nav-link text-center loading-confirm", confirm: "ログアウトしますか?" %></li>
        <% else %>
          <li><%= link_to "Facebookでログイン", "/auth/facebook", class: "nav-link text-center loading" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Metroku</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta content="width=device-width, initial-scale=1" name="viewport">
</head>
<body>
  <div id="wrap">
    <%= render 'layouts/header' %>

    <% flash.each do |key, value| %>
      <div class="alert alert-dismissable alert-warning" style="margin: 0px;">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <h4><%= value %></h4>
      </div>
    <% end %>

    <div id="contents" style="height: 100%;">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </div>
  <div id="before_start_app" class="jumbotron"
     style="margin: 0 auto; width: 95%; height: 250px; opacity: 1.0; background-color: #428bca; color: white; position: relative; top: -500px; display: none;">
      <div class="panel-body" style="font-size: 20px;">ようこそ 『メトろく』へ</div>
      <div style="margin: 0 auto; width: 95%; margin: 2px; font-size=15px">
      <p style="margin: 3px">メトろくは東京メトロ銀座線をすごろく形式で旅するアプリです。</p>
      <p style="margin: 3px">サイコロを振り、各駅に存在するミッションをクリアしながら、終着の浅草駅を目指してください。</p>
      <p style="margin: 3px">それでは、いい旅になることを祈っています。</p>
    </div>
    <a id="getting_start_app" class="btn btn-danger" style="margin: 0 auto; display: block; width: 80%;">アプリを開始</a>
  </div>
    <div id="loading" style="opacity: 1.0; display: none; z-index: 10;">
      <div style="background-color: white; width: 200px; height: 200px; border-radius: 20px; margin: 0 auto; position: relative; top: 25%;">
        <div style="text-align: center; height: 40%; width: 100px; margin: 0 auto; padding-top: 40px;">Now Loading...</div>
        <div style="width: 100px; margin: 0 auto;">
          <img src=<%= asset_path "loading.gif" %> style="display: block; margin: 0 auto;">
        </div>
      </div>
    </div>
</body>
<style>
html, body {
	height: 100%;
}
body {
  background-color: black;
}
#wrap {
    width: 100%;
    position: relative;
    min-height: 100%;	
    background-color: white;
    color: black;
}
#contents {
	padding-bottom: 100px;
}
#footer {
	position: absolute;
	bottom: 0;
	width: 100%;
}

#loading {
  width: 100%; /* gif画像の幅 */
  height: 100%; /* gif画像の高さ */
  padding: 20px; /* gif画像を大きく */
  position: fixed; /* gif画像をスクロールさせない */
  top: 0; /* gif画像を画面縦中央へ */
}

</style>
<script>
nowLoadingStart = function() {
    $('#wrap').css('opacity', 0.25);
    $('#loading').css('display', '');
}

nowLoadingStop = function() {
    $('#wrap').css('opacity', 1);
    $('#loading').css('display', 'none');
}
</script>
</html>